### ISSUE TITLE
Does it support to redmine 4.0 ?

### ISSUE THREAD

**Issue by darklord1990** [biow0lf/redmine_landing_page#16]
did anyone test with redmine 4.0 ?

**Comment by Silex** [comment]
A similar change than https://github.com/Shopify/shopify_app/pull/404/commits/fae3b2496b000db781a267cfcb2c7489e09f2be1 needs to be applied.

**Comment by andreav** [comment]
I tested it on Redmine 4.1.1 and I got this error during redmine:plugins migrate:

```
C:\Bitnami\redmine-4.1.1-2\apps\redmine\htdocs>ruby bin\rake redmine:plugins RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/plugins/redmine_landing_page/init.rb:12:in `<top (required)>'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in
 require'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dep
endency'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'

C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/lib/redmine/plugin.rb:181:in `block in load'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/lib/redmine/plugin.rb:172:in `each'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/lib/redmine/plugin.rb:172:in `load'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/config/initializers/30-redmine.rb:20:in `<top (required)>'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in
 load'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dep
endency'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initial
izer'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrum
ent'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:E
ngine>'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializ
ers'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_bloc
ks'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
C:/Bitnami/redmine-4.1.1-2/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by andreav** [comment]
I can confirm that the solution provided by @Silex  is working!

**Comment by acosonic** [comment]
It's failing on 4.1

bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddLandingPageToProjects < ActiveRecord::Migration[4.2]
/home/redmine/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:528:in `inherited'
/home/redmine/redmine/plugins/redmine_landing_page/db/migrate/001_

**Comment by Danilovt** [comment]
I can confirm It works on Redmine 4.1
First I did solution provided by @Silex .
After "specify the Rails release" error i just put the correct version inside brackets (...ActiveRecord::Migration[5.2]) in all db files
Then I run bundle exec rake redmine:plugins:migrate and finally restarted redmine.

Reference: https://stackoverflow.com/questions/48815984/rails5-directly-inheriting-from-from-activerecordmigration-is-not-supported-s
